export const ANALYSIS_CONSTANTS = {
    ANALYSIS_PROVIDER: "google",

    ANALYSIS_MODEL_NAME: "gemini-2.5-flash",

    EMBEDDING_PROVIDER: "google",
    EMBEDDING_MODEL_NAME: "gemini-embedding-001",

    EMBEDDING_DIMENSIONS : 768,

    DEFAULT_SIMILARITY_THRESHOLD : 0.92,

    DEFAULT_RETRIEVAL_LIMIT : 10,

    DEFAULT_THEME_COLOR: "#64748B"
}